<script lang="ts">
	/** Terms page — plain-English terms of use. */
</script>

<article class="legal">
	<h1 class="title">Terms</h1>
	<p class="updated">Last updated: August 2026</p>

	<section>
		<h2>What URLyze does</h2>
		<p>
			URLyze turns a link you provide into three text artifacts — an executive sketch, study
			notes, and a slide outline. It's a tool for reading and studying public content.
		</p>
	</section>

	<section>
		<h2>Using the service</h2>
		<p>
			Use URLyze for lawful purposes. Don't use it to harass, to reproduce copyrighted work at
			scale, or to probe or attack other people's systems. Automated high-volume use is subject
			to rate limits; we may slow or block traffic we believe is abusive.
		</p>
	</section>

	<section>
		<h2>Content and ownership</h2>
		<p>
			The artifacts we generate are based on content you pointed us at; you're responsible for
			how you use them. The text you download is yours to keep. We make no claim of ownership
			over the source material, which belongs to its authors.
		</p>
	</section>

	<section>
		<h2>Availability</h2>
		<p>
			We aim to keep URLyze up and accurate, but it's provided "as is" with no warranty.
			Artifacts are generated by AI and can be wrong or miss context — verify important facts
			against the source.
		</p>
	</section>
</article>

<style>
	.legal {
		max-width: 640px;
		margin: 0 auto;
		padding: var(--space-xxl) var(--space-md);
		display: flex;
		flex-direction: column;
		gap: var(--space-lg);
	}
	.title {
		margin: 0;
		font-family: var(--font-display);
		font-size: clamp(28px, 5vw, 40px);
		font-weight: 400;
		letter-spacing: -0.02em;
	}
	.updated {
		margin: 0;
		font-size: 13px;
		color: var(--text-faint);
	}
	section {
		display: flex;
		flex-direction: column;
		gap: var(--space-xs);
	}
	h2 {
		margin: 0;
		font-size: 18px;
		font-weight: 600;
	}
	p {
		margin: 0;
		font-size: 15px;
		line-height: 1.65;
		color: var(--text-secondary);
	}
</style>
