import { describe, it, expect } from 'vitest';
import { slugify, buildTxtContent, buildMdContent } from '$lib/client/downloads';
import type { AnalysisResult } from '$lib/types/analysis';

const RESULT: AnalysisResult = {
	id: 'row-1',
	title: 'Why Dogs Dream',
	sourceType: 'WEBPAGE',
	originalUrl: 'https://example.com/dogs',
	sourceMetadata: {},
	quality: 'HIGH',
	extractionLabel: 'Full article',
	model: 'gemini-2.5-flash',
	summary: 'Dogs dream during REM sleep.',
	notes: 'Points about sleep cycles.',
	pptContent: [
		{ title: 'Intro', points: ['What REM is', 'Why it matters'] },
		{ title: 'Evidence', points: ['EEG studies', 'Behavior', 'Vet guidance'] }
	],
	createdAt: '2026-08-09T12:00:00Z'
};

describe('client/downloads', () => {
	describe('slugify', () => {
		it('lowercases and joins on non-alphanumerics', () => {
			expect(slugify('Why Dogs Dream!')).toBe('why-dogs-dream');
		});

		it('strips leading and trailing separators', () => {
			expect(slugify('  --GEMINI Notes--  ')).toBe('gemini-notes');
		});

		it('caps the length at 60 chars', () => {
			expect(slugify('a'.repeat(100))).toHaveLength(60);
		});

		it('falls back when nothing survives', () => {
			expect(slugify('!!!--!!!')).toBe('analysis');
			expect(slugify('')).toBe('analysis');
		});
	});

	describe('buildTxtContent', () => {
		it('lays out title, source and the three sections', () => {
			const txt = buildTxtContent(RESULT);
			expect(txt).toContain('Why Dogs Dream');
			expect(txt).toContain('Source: https://example.com/dogs');
			expect(txt).toContain('=== EXECUTIVE SKETCH ===');
			expect(txt).toContain('=== STUDY NOTES ===');
			expect(txt).toContain('=== SLIDE OUTLINE ===');
		});

		it('numbers slides and indents their points', () => {
			const txt = buildTxtContent(RESULT);
			expect(txt).toContain('1. Intro');
			expect(txt).toContain('   - What REM is');
			expect(txt).toContain('2. Evidence');
		});

		it('stamps a dated footer', () => {
			expect(buildTxtContent(RESULT)).toMatch(/Generated by URLyze · \d{4}-\d{2}-\d{2}/);
		});
	});

	describe('buildMdContent', () => {
		it('uses a heading hierarchy for the three artifacts', () => {
			const md = buildMdContent(RESULT);
			expect(md).toContain('# Why Dogs Dream');
			expect(md).toContain('## Executive sketch');
			expect(md).toContain('## Study notes');
			expect(md).toContain('## Slide outline');
			expect(md).toContain('**Source:** https://example.com/dogs');
		});

		it('formats slides as ### headings with bullet points', () => {
			const md = buildMdContent(RESULT);
			expect(md).toContain('### 1. Intro');
			expect(md).toContain('- What REM is');
		});
	});
});
