import type { AnalysisResult } from '$lib/types/analysis';

/**
 * Client-side downloads for the three artifacts. .txt and .md are built as
 * Blobs and saved without any dependency; .pptx loads pptxgenjs lazily so the
 * heavy library never enters the initial bundle.
 */

/** Turn a title into a safe filename slug (letters, digits, dash, underscore). */
export function slugify(title: string): string {
	return (
		title
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/^-+|-+$/g, '')
			.slice(0, 60) || 'analysis'
	);
}

function triggerDownload(blob: Blob, filename: string): void {
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	document.body.appendChild(a);
	a.click();
	a.remove();
	setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Plain-text version: title, metadata line, then the three artifacts. */
export function downloadTxt(result: AnalysisResult): void {
	const text = buildTxtContent(result);
	triggerDownload(new Blob([text], { type: 'text/plain;charset=utf-8' }), `${slugify(result.title)}.txt`);
}

/** Markdown version with proper heading hierarchy. */
export function downloadMd(result: AnalysisResult): void {
	const md = buildMdContent(result);
	triggerDownload(new Blob([md], { type: 'text/markdown;charset=utf-8' }), `${slugify(result.title)}.md`);
}

/** The full .txt payload — pure, so it can be unit-tested without a DOM. */
export function buildTxtContent(result: AnalysisResult): string {
	const slides = result.pptContent
		.map((s, i) => `${i + 1}. ${s.title}\n   - ${s.points.join('\n   - ')}`)
		.join('\n\n');
	return [
		result.title,
		`Source: ${result.originalUrl}`,
		'',
		'=== EXECUTIVE SKETCH ===',
		result.summary,
		'',
		'=== STUDY NOTES ===',
		result.notes,
		'',
		'=== SLIDE OUTLINE ===',
		slides,
		'',
		`Generated by URLyze · ${new Date().toISOString().slice(0, 10)}`
	].join('\n\n');
}

/** The full .md payload — pure, so it can be unit-tested without a DOM. */
export function buildMdContent(result: AnalysisResult): string {
	const slides = result.pptContent
		.map((s, i) => `### ${i + 1}. ${s.title}\n${s.points.map((p) => `- ${p}`).join('\n')}`)
		.join('\n\n');
	return [
		`# ${result.title}`,
		`**Source:** ${result.originalUrl}`,
		'',
		'## Executive sketch',
		result.summary,
		'',
		'## Study notes',
		result.notes,
		'',
		'## Slide outline',
		slides,
		'',
		`*Generated by [URLyze](/) · ${new Date().toISOString().slice(0, 10)}*`
	].join('\n\n');
}

/**
 * PowerPoint version, re-themed to the DESIGN.md palette. pptxgenjs is
 * imported lazily — it only loads when the user actually clicks the button.
 */
export async function downloadPptx(result: AnalysisResult): Promise<void> {
	const { default: PptxGenJS } = await import('pptxgenjs');
	const pptx = new PptxGenJS();
	pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
	pptx.layout = 'WIDE';
	pptx.theme = {
		headFontFace: 'Inter',
		bodyFontFace: 'Inter'
	};

	const INK = '1F1F1F';
	const PRIMARY = 'FA520F';
	const CREAM = 'FFF8E0';

	const titleSlide = pptx.addSlide();
	titleSlide.background = { color: CREAM };
	titleSlide.addText(result.title, {
		x: 0.6,
		y: 1.6,
		w: 12,
		h: 1.8,
		fontSize: 34,
		bold: true,
		color: INK,
		fontFace: 'Inter'
	});
	titleSlide.addText(result.originalUrl, {
		x: 0.6,
		y: 3.6,
		w: 12,
		h: 0.6,
		fontSize: 14,
		color: PRIMARY
	});

	for (const slide of result.pptContent) {
		const s = pptx.addSlide();
		s.background = { color: 'FFFFFF' };
		s.addText(slide.title, {
			x: 0.6,
			y: 0.5,
			w: 12,
			h: 0.9,
			fontSize: 26,
			bold: true,
			color: PRIMARY
		});
		s.addText(
			slide.points.map((p) => ({ text: p, options: { bullet: { characterCode: '2022' } } })),
			{
				x: 0.7,
				y: 1.7,
				w: 11.9,
				h: 5.2,
				fontSize: 18,
				color: INK,
				lineSpacingMultiple: 1.4
			}
		);
	}

	await pptx.writeFile({ fileName: `${slugify(result.title)}.pptx` });
}
